2022-04-20 14:09:37,354 - Accepting connection from: 172.17.0.1:47298
2022-04-20 14:09:37,358 -     bart_pulseq
2022-04-20 14:09:37,388 - Data is from a SIEMENS Investigational_Device_7T_Plus at 7.0T
2022-04-20 14:09:37,396 - Starting bart_pulseq processing based on config
2022-04-20 14:09:37,397 - No metadata file available.
Traceback (most recent call last):
  File "/opt/code/python-ismrmrd-server/server.py", line 82, in handle
    bart_pulseq.process(connection, config, hdr)
  File "/opt/code/python-ismrmrd-server/bart_pulseq.py", line 35, in process
    raise ValueError("No metadata file available.")
ValueError: No metadata file available.
2022-04-20 14:09:37,402 - Socket closed
